version: '3.8'
name: fincheck
services:
  database:
    image: postgres
    volumes:
      - fincheck_pg_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: fincheck-database
    ports:
      - '5432:5432'

volumes:
  fincheck_pg_data:
